name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        image: ["ubuntu:24.04"]
        arch: ["X64", "ARM64"]
    container: ${{ matrix.image }}
    runs-on: [self-hosted, "${{ matrix.arch }}"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies (Ubuntu)
        if: matrix.image == 'ubuntu:24.04'
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install \
            bison \
            clang \
            clang-format \
            clang-tidy \
            cmake \
            doxygen \
            flex \
            furo \
            git \
            jq \
            lcov \
            libbpf-dev \
            libcmocka-dev \
            libnl-3-dev \
            linux-tools-common \
            python3-breathe \
            python3-pip \
            python3-sphinx \
            pkgconf && \
          pip3 install --break-system-packages linuxdoc
      - name: Configure build
        run: cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build
      - name: Build
        run: make -C $GITHUB_WORKSPACE/build
      - name: Run unit tests
        run: make -C $GITHUB_WORKSPACE/build test
