name: CI

on:
  push:
    branches:
      - "**"

permissions:
  checks: write
  pull-requests: write

jobs:
  full:
    strategy:
      fail-fast: false
      matrix:
        # This forces GitHub to print "ubuntu:24.04, x64" in the job name.
        image: [ "ubuntu:24.04" ]
        arch: [ "X64", "ARM64" ]
        mode: ["release"]
    container: "${{ matrix.system }}"
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies (Ubuntu)
        if: matrix.image == 'ubuntu:24.04'
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install \
            bison \
            clang \
            clang-format \
            clang-tidy \
            cmake \
            doxygen \
            flex \
            furo \
            git \
            jq \
            lcov \
            libbpf-dev \
            libcmocka-dev \
            libnl-3-dev \
            linux-tools-common \
            python3-breathe \
            python3-pip \
            python3-sphinx \
            pkgconf && \
          pip3 install --break-system-packages linuxdoc
      - name: Configure build
        run: cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build -DCMAKE_BUILD_TYPE=${{ matrix.mode }}
      - name: Build
        run: make -C $GITHUB_WORKSPACE/build
      - name: Check style
        run: make -C $GITHUB_WORKSPACE/build check
      - name: Generate documentation
        run: make -C $GITHUB_WORKSPACE/build doc
