name: CI-v2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write

jobs:
  full:
    strategy:
      fail-fast: false
      matrix:
        system: ["fedora:40"]
        arch: ["X64", "ARM64"]
        mode: ["release"]
    container: "${{ matrix.system }}"
    runs-on: ["ubuntu-latest"]
    steps:
      - name: CheckOut SCM Code
        uses: actions/checkout@v4
      - name: Install Dependencies (Fedora)
        run: |
          sudo dnf --disablerepo=* --enablerepo=fedora,updates --setopt=install_weak_deps=False -y install \
            bison \
            bpftool \
            clang \
            clang-tools-extra \
            cmake \
            doxygen \
            flex \
            git \
            jq \
            lcov \
            pkgconf \ 
            autoconf \
            automake \
            gmp-devel \
            libedit-devel \
            libmnl-devel \
            libnftnl-devel \
            libtool \
            libasan \
            libbpf-devel \
            libcmocka-devel \
            libnl3-devel \
            libubsan \
            python3-breathe \
            python3-furo \
            python3-linuxdoc \
            python3-sphinx
      - name: Prepare Build (core)
        run: cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build -DCMAKE_BUILD_TYPE=${{ matrix.mode }}
      - name: Build BPFilter
        run: make -C $GITHUB_WORKSPACE/build
      - name: Build NFTables
        run: make -C $GITHUB_WORKSPACE/build nftables
      - name: Check Style
        run: make -C $GITHUB_WORKSPACE/build check
      - name: Generate Documentation
        run: make -C $GITHUB_WORKSPACE/build doc