name: CI-v2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write

jobs:
  full:
    strategy:
      fail-fast: false
      matrix:
        system: ["ubuntu:24.04"]
        arch: ["ARM64"]
        mode: ["release"]
    container: "${{ matrix.system }}"
    runs-on: ["ubuntu-latest"]
    steps:
      - name: CheckOut SCM Code
        uses: actions/checkout@v4
      - name: Install Dependencies (Ubuntu)
        run: |
          apt-get update && \
            DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install \
              autoconf \
              bison \
              clang \
              clang-format \
              clang-tidy \
              cmake \
              doxygen \
              flex \
              furo \
              git \
              jq \
              lcov \
              libbpf-dev \
              libcmocka-dev \
              libnl-3-dev \
              linux-tools-common \
              python3-breathe \
              python3-pip \
              python3-sphinx \
              pkgconf \
              libedit-dev \
              libgmp-dev \
              libmnl-dev \
              libnftnl-dev \
              libtool && \
          pip3 install --break-system-packages linuxdoc
      - name: Prepare Build (core)
        run: cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build -DCMAKE_BUILD_TYPE=${{ matrix.mode }}
      - name: Build BPFilter
        run: make -C $GITHUB_WORKSPACE/build
      - name: Build NFTables
        run: make -C $GITHUB_WORKSPACE/build nftables
      - name: Check Style
        run: make -C $GITHUB_WORKSPACE/build check
      - name: Generate Documentation
        run: make -C $GITHUB_WORKSPACE/build doc
      - name: Prepare Build Artifacts (bpfilter-core, bpfilter-nftables)
        run: |
          tar -czvf ${{ matrix.mode }}-bpfilter-core-${{ matrix.arch }}.tar.gz ./build/output/* && \
          tar -czvf ${{ matrix.mode }}-bpfilter-nftables-${{ matrix.arch }}.tar.gz ./build/tools/install/*
      - name: Upload Core Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bpfilter-${{ matrix.arch }}-${{ matrix.mode }}
          path: ${{ matrix.mode }}-bpfilter-core-${{ matrix.arch }}.tar.gz
      - name: Upload NFTables Install-Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bpfilter-nftables-${{ matrix.arch }}-${{ matrix.mode }}
          path: ${{ matrix.mode }}-bpfilter-nftables-${{ matrix.arch }}.tar.gz
